image: docker

services:
  - docker:bind

stages:
  - deploy

develop:
  stage: deploy
  only:
    - develop
  script:
    - cp .env.staging .env
    - docker-compose -f docker-compose.stage.yml down
    - docker-compose -f docker-compose.stage.yml up -d --build
